### ISSUE TITLE
主页面底部菜单栏显示背景bug

### ISSUE THREAD

**Issue by everhad** [idlestars/LogCollect#1]
主页面底部菜单栏显示背景bug：在增加了MainActivity其它View的点击事件后，之前处理底部菜单栏点击事件的逻辑有问题了。应该把对底部菜单栏四个view的点击处理放在单独的onClickListener对象中。
@TheFifthHeaven

**Comment by TheFifthHeaven** [comment]
将MainActivity底部的四个菜单view的点击事件单独指定一个onclickListener。
